version: "2"

services:
  odoo15:
    build:
      context: ./odoo
    image: odoo:15.0
    container_name: odoo15
    command: -- --dev=reload
    depends_on:
      - odoo15_db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons:rw
    environment: 
      - HOST=odoo15_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  odoo15_db:
    image: postgres:13
    container_name: odoo15_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data: